version: "3.4"

services:
  api:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    container_name: "survey-gorilla-api"
    volumes:
      - "./:/usr/src/app"
    ports:
      - "8080:8080"
    stdin_open: true
    depends_on:
      - postgres-db
    environment:
      - APP_PORT=8080
      - APP_URL=http://localhost
      - POSTGRES_USER=gorilla
      - POSTGRES_DB_NAME=survey_gorilla
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB_HOST=postgres-db
      - POSTGRES_PORT=5432
      - NODE_ENV=development
  postgres-db:
    image: postgres:13.0-alpine
    container_name: "survey-gorilla-db"
    ports:
      - "5432:5432"
    volumes:
      - ./compose/.postgresVolume:/var/lib/postgresql/data
      - ./compose/pgInit:/docker-entrpoint-initdb.d
    environment:
      - POSTGRES_USER=gorilla
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=survey_gorilla
      - POSTRGRES_HOST_AUTH_METHOD=trust
